// بنك الكلمات للعبة "احزر الكلمة" - كل كلمة عربية فصحى بدون تشكيل، مع فئة تستخدم في زر التلميح
// طول الكلمات يتراوح بين 3 و21 حرفاً (العناوين متعددة الكلمات مفصولة بمسافة) ويُختار عشوائياً عند بدء كل جولة

const WORDS = [
  // ===================== دولة =====================
  { word: "مصر", category: "دولة" }, { word: "قطر", category: "دولة" },
  { word: "عمان", category: "دولة" }, { word: "تونس", category: "دولة" },
  { word: "ليبيا", category: "دولة" }, { word: "سوريا", category: "دولة" },
  { word: "اليمن", category: "دولة" }, { word: "لبنان", category: "دولة" },
  { word: "الهند", category: "دولة" }, { word: "الصين", category: "دولة" },
  { word: "العراق", category: "دولة" }, { word: "المغرب", category: "دولة" },
  { word: "الاردن", category: "دولة" }, { word: "السودان", category: "دولة" },
  { word: "الجزائر", category: "دولة" }, { word: "البحرين", category: "دولة" },
  { word: "الصومال", category: "دولة" }, { word: "السعودية", category: "دولة" },
  { word: "فرنسا", category: "دولة" }, { word: "اسبانيا", category: "دولة" },
  { word: "ايطاليا", category: "دولة" }, { word: "المانيا", category: "دولة" },
  { word: "بريطانيا", category: "دولة" }, { word: "اليابان", category: "دولة" },
  { word: "كوريا", category: "دولة" }, { word: "تركيا", category: "دولة" },
  { word: "اليونان", category: "دولة" }, { word: "روسيا", category: "دولة" },
  { word: "امريكا", category: "دولة" }, { word: "كندا", category: "دولة" },
  { word: "البرازيل", category: "دولة" }, { word: "الارجنتين", category: "دولة" },
  { word: "نيجيريا", category: "دولة" }, { word: "كينيا", category: "دولة" },
  { word: "اثيوبيا", category: "دولة" }, { word: "غانا", category: "دولة" },
  { word: "فلسطين", category: "دولة" }, { word: "باكستان", category: "دولة" },
  { word: "ايران", category: "دولة" }, { word: "ماليزيا", category: "دولة" },
  { word: "اندونيسيا", category: "دولة" }, { word: "تايلاند", category: "دولة" },
  { word: "الفلبين", category: "دولة" }, { word: "استراليا", category: "دولة" },
  { word: "النمسا", category: "دولة" }, { word: "سويسرا", category: "دولة" },
  { word: "هولندا", category: "دولة" }, { word: "البرتغال", category: "دولة" },

  // ===================== تاريخ =====================
  { word: "حرب", category: "تاريخ" }, { word: "فتح", category: "تاريخ" },
  { word: "غزو", category: "تاريخ" }, { word: "عصر", category: "تاريخ" },
  { word: "قرن", category: "تاريخ" }, { word: "زمن", category: "تاريخ" },
  { word: "ثورة", category: "تاريخ" }, { word: "معركة", category: "تاريخ" },
  { word: "حضارة", category: "تاريخ" }, { word: "وثيقة", category: "تاريخ" },
  { word: "تحرير", category: "تاريخ" }, { word: "مملكة", category: "تاريخ" },
  { word: "خلافة", category: "تاريخ" }, { word: "معاهدة", category: "تاريخ" },
  { word: "احتلال", category: "تاريخ" }, { word: "استقلال", category: "تاريخ" },
  { word: "استعمار", category: "تاريخ" }, { word: "امبراطورية", category: "تاريخ" },
  { word: "جيش", category: "تاريخ" }, { word: "سلاح", category: "تاريخ" },
  { word: "قصر", category: "تاريخ" }, { word: "تاج", category: "تاريخ" },
  { word: "عرش", category: "تاريخ" }, { word: "وزير", category: "تاريخ" },
  { word: "امير", category: "تاريخ" }, { word: "سلطنة", category: "تاريخ" },
  { word: "امارة", category: "تاريخ" }, { word: "دستور", category: "تاريخ" },
  { word: "برلمان", category: "تاريخ" }, { word: "انقلاب", category: "تاريخ" },
  { word: "هدنة", category: "تاريخ" }, { word: "حصار", category: "تاريخ" },
  { word: "غزوة", category: "تاريخ" }, { word: "فتوحات", category: "تاريخ" },
  { word: "اثار", category: "تاريخ" }, { word: "متحف", category: "تاريخ" },
  { word: "تراث", category: "تاريخ" },

  // ===================== حيوان =====================
  { word: "اسد", category: "حيوان" }, { word: "نمر", category: "حيوان" },
  { word: "ذئب", category: "حيوان" }, { word: "فيل", category: "حيوان" },
  { word: "جمل", category: "حيوان" }, { word: "قرد", category: "حيوان" },
  { word: "نسر", category: "حيوان" }, { word: "صقر", category: "حيوان" },
  { word: "حوت", category: "حيوان" }, { word: "قطة", category: "حيوان" },
  { word: "كلب", category: "حيوان" }, { word: "حصان", category: "حيوان" },
  { word: "ارنب", category: "حيوان" }, { word: "ثعلب", category: "حيوان" },
  { word: "خروف", category: "حيوان" }, { word: "غزال", category: "حيوان" },
  { word: "بومة", category: "حيوان" }, { word: "زرافة", category: "حيوان" },
  { word: "تمساح", category: "حيوان" }, { word: "فراشة", category: "حيوان" },
  { word: "عصفور", category: "حيوان" }, { word: "حمامة", category: "حيوان" },
  { word: "دجاجة", category: "حيوان" }, { word: "عنكبوت", category: "حيوان" },
  { word: "باندا", category: "حيوان" }, { word: "كنغر", category: "حيوان" },
  { word: "دب", category: "حيوان" }, { word: "سلحفاة", category: "حيوان" },
  { word: "ضفدع", category: "حيوان" }, { word: "حرباء", category: "حيوان" },
  { word: "بجعة", category: "حيوان" }, { word: "بطة", category: "حيوان" },
  { word: "ديك", category: "حيوان" }, { word: "خفاش", category: "حيوان" },
  { word: "قنفذ", category: "حيوان" }, { word: "حلزون", category: "حيوان" },
  { word: "نحلة", category: "حيوان" }, { word: "دبور", category: "حيوان" },
  { word: "جراد", category: "حيوان" }, { word: "اخطبوط", category: "حيوان" },
  { word: "دولفين", category: "حيوان" }, { word: "قرش", category: "حيوان" },
  { word: "حمار", category: "حيوان" }, { word: "بغل", category: "حيوان" },
  { word: "ماعز", category: "حيوان" }, { word: "خنزير", category: "حيوان" },

  // ===================== طعام =====================
  { word: "خبز", category: "طعام" }, { word: "تمر", category: "طعام" },
  { word: "ارز", category: "طعام" }, { word: "لحم", category: "طعام" },
  { word: "سمك", category: "طعام" }, { word: "عسل", category: "طعام" },
  { word: "موز", category: "طعام" }, { word: "شاي", category: "طعام" },
  { word: "جبن", category: "طعام" }, { word: "سكر", category: "طعام" },
  { word: "ملح", category: "طعام" }, { word: "زيت", category: "طعام" },
  { word: "خيار", category: "طعام" }, { word: "زبدة", category: "طعام" },
  { word: "حليب", category: "طعام" }, { word: "قهوة", category: "طعام" },
  { word: "عصير", category: "طعام" }, { word: "تفاح", category: "طعام" },
  { word: "فطور", category: "طعام" }, { word: "خيارة", category: "طعام" },
  { word: "فاكهة", category: "طعام" }, { word: "برتقال", category: "طعام" },
  { word: "طماطم", category: "طعام" }, { word: "بطاطا", category: "طعام" },
  { word: "مكرونة", category: "طعام" }, { word: "بيتزا", category: "طعام" },
  { word: "برغر", category: "طعام" }, { word: "شاورما", category: "طعام" },
  { word: "كبسة", category: "طعام" }, { word: "مندي", category: "طعام" },
  { word: "مجبوس", category: "طعام" }, { word: "هريس", category: "طعام" },
  { word: "سمبوسة", category: "طعام" }, { word: "كنافة", category: "طعام" },
  { word: "بقلاوة", category: "طعام" }, { word: "لقيمات", category: "طعام" },
  { word: "مهلبية", category: "طعام" }, { word: "شوكولاته", category: "طعام" },
  { word: "بسكويت", category: "طعام" }, { word: "كيك", category: "طعام" },
  { word: "فطيرة", category: "طعام" }, { word: "سلطة", category: "طعام" },
  { word: "شوربة", category: "طعام" }, { word: "عدس", category: "طعام" },
  { word: "فول", category: "طعام" }, { word: "حمص", category: "طعام" },

  // ===================== مهنة =====================
  { word: "طبيب", category: "مهنة" }, { word: "معلم", category: "مهنة" },
  { word: "شرطي", category: "مهنة" }, { word: "طيار", category: "مهنة" },
  { word: "نجار", category: "مهنة" }, { word: "حداد", category: "مهنة" },
  { word: "خياط", category: "مهنة" }, { word: "طباخ", category: "مهنة" },
  { word: "صياد", category: "مهنة" }, { word: "ممرض", category: "مهنة" },
  { word: "صحفي", category: "مهنة" }, { word: "مصور", category: "مهنة" },
  { word: "نادل", category: "مهنة" }, { word: "بحار", category: "مهنة" },
  { word: "جندي", category: "مهنة" }, { word: "مهندس", category: "مهنة" },
  { word: "محامي", category: "مهنة" }, { word: "مزارع", category: "مهنة" },
  { word: "قاضي", category: "مهنة" }, { word: "محرر", category: "مهنة" },
  { word: "مترجم", category: "مهنة" }, { word: "مبرمج", category: "مهنة" },
  { word: "محاسب", category: "مهنة" }, { word: "مصمم", category: "مهنة" },
  { word: "مدرب", category: "مهنة" }, { word: "حلاق", category: "مهنة" },
  { word: "سباك", category: "مهنة" }, { word: "كهربائي", category: "مهنة" },
  { word: "دهان", category: "مهنة" }, { word: "خباز", category: "مهنة" },
  { word: "جزار", category: "مهنة" }, { word: "بائع", category: "مهنة" },
  { word: "سائق", category: "مهنة" }, { word: "مضيف", category: "مهنة" },
  { word: "ممثل", category: "مهنة" }, { word: "مخرج", category: "مهنة" },
  { word: "كاتب", category: "مهنة" }, { word: "شاعر", category: "مهنة" },

  // ===================== مكان =====================
  { word: "جبل", category: "مكان" }, { word: "نهر", category: "مكان" },
  { word: "بحر", category: "مكان" }, { word: "وادي", category: "مكان" },
  { word: "جسر", category: "مكان" }, { word: "نفق", category: "مكان" },
  { word: "سوق", category: "مكان" }, { word: "غابة", category: "مكان" },
  { word: "واحة", category: "مكان" }, { word: "شلال", category: "مكان" },
  { word: "قلعة", category: "مكان" }, { word: "مطار", category: "مكان" },
  { word: "محطة", category: "مكان" }, { word: "مسجد", category: "مكان" },
  { word: "صحراء", category: "مكان" }, { word: "جزيرة", category: "مكان" },
  { word: "بحيرة", category: "مكان" }, { word: "ميناء", category: "مكان" },
  { word: "كهف", category: "مكان" }, { word: "تلة", category: "مكان" },
  { word: "هضبة", category: "مكان" }, { word: "سهل", category: "مكان" },
  { word: "خليج", category: "مكان" }, { word: "مضيق", category: "مكان" },
  { word: "منتزه", category: "مكان" }, { word: "سد", category: "مكان" },
  { word: "بركان", category: "مكان" }, { word: "منارة", category: "مكان" },
  { word: "مرسى", category: "مكان" }, { word: "رصيف", category: "مكان" },
  { word: "استاد", category: "مكان" }, { word: "ملعب", category: "مكان" },
  { word: "فندق", category: "مكان" }, { word: "متجر", category: "مكان" },
  { word: "مصنع", category: "مكان" }, { word: "مزرعة", category: "مكان" },
  { word: "سفارة", category: "مكان" }, { word: "بلدية", category: "مكان" },

  // ===================== عام =====================
  { word: "قلم", category: "عام" }, { word: "باب", category: "عام" },
  { word: "كتاب", category: "عام" }, { word: "ساعة", category: "عام" },
  { word: "شباك", category: "عام" }, { word: "مكتب", category: "عام" },
  { word: "مطبخ", category: "عام" }, { word: "غرفة", category: "عام" },
  { word: "هاتف", category: "عام" }, { word: "سرير", category: "عام" },
  { word: "مراة", category: "عام" }, { word: "مصباح", category: "عام" },
  { word: "تلفاز", category: "عام" }, { word: "مدرسة", category: "عام" },
  { word: "مكتبة", category: "عام" }, { word: "حديقة", category: "عام" },
  { word: "سيارة", category: "عام" }, { word: "طائرة", category: "عام" },
  { word: "حاسوب", category: "عام" }, { word: "مفتاح", category: "عام" },
  { word: "سلطان", category: "عام" }, { word: "جميلة", category: "عام" },
  { word: "كبيرة", category: "عام" }, { word: "صغيرة", category: "عام" },
  { word: "جريدة", category: "عام" }, { word: "مدينة", category: "عام" },
  { word: "قصيدة", category: "عام" }, { word: "حقيبة", category: "عام" },
  { word: "عاصمة", category: "عام" }, { word: "جامعة", category: "عام" },
  { word: "سفينة", category: "عام" }, { word: "طويلة", category: "عام" },
  { word: "قصيرة", category: "عام" }, { word: "جديدة", category: "عام" },
  { word: "قديمة", category: "عام" }, { word: "رخيصة", category: "عام" },
  { word: "غالية", category: "عام" }, { word: "لذيذة", category: "عام" },
  { word: "باردة", category: "عام" }, { word: "سعيدة", category: "عام" },
  { word: "حزينة", category: "عام" }, { word: "نظيفة", category: "عام" },
  { word: "سريعة", category: "عام" }, { word: "بطيئة", category: "عام" },
  { word: "ثقيلة", category: "عام" }, { word: "خفيفة", category: "عام" },
  { word: "عريضة", category: "عام" }, { word: "مريضة", category: "عام" },
  { word: "جائعة", category: "عام" }, { word: "عطشان", category: "عام" },
  { word: "غضبان", category: "عام" }, { word: "فرحان", category: "عام" },
  { word: "تعبان", category: "عام" }, { word: "كسلان", category: "عام" },
  { word: "شجاعة", category: "عام" }, { word: "كريمة", category: "عام" },
  { word: "بخيلة", category: "عام" }, { word: "صادقة", category: "عام" },
  { word: "كاذبة", category: "عام" }, { word: "مجتهد", category: "عام" },
  { word: "طاولة", category: "عام" }, { word: "عمارة", category: "عام" },
  { word: "سحابة", category: "عام" }, { word: "بستان", category: "عام" },
  { word: "كنيسة", category: "عام" }, { word: "دراجة", category: "عام" },
  { word: "مروحة", category: "عام" }, { word: "غسالة", category: "عام" },
  { word: "ثلاجة", category: "عام" }, { word: "فرن", category: "عام" },
  { word: "صحن", category: "عام" }, { word: "ملعقة", category: "عام" },
  { word: "شوكة", category: "عام" }, { word: "سكين", category: "عام" },
  { word: "كوب", category: "عام" }, { word: "وسادة", category: "عام" },
  { word: "بطانية", category: "عام" }, { word: "ستارة", category: "عام" },
  { word: "سجادة", category: "عام" }, { word: "محفظة", category: "عام" },
  { word: "نظارة", category: "عام" }, { word: "قبعة", category: "عام" },
  { word: "حذاء", category: "عام" }, { word: "قميص", category: "عام" },
  { word: "بنطال", category: "عام" }, { word: "فستان", category: "عام" },
  { word: "معطف", category: "عام" }, { word: "جوارب", category: "عام" },

  // ===================== أنميات =====================
  { word: "ناروتو", category: "أنميات" }, { word: "بوكيمون", category: "أنميات" },
  { word: "المحقق كونان", category: "أنميات" }, { word: "بليتش", category: "أنميات" },
  { word: "دورايمون", category: "أنميات" }, { word: "سلام دانك", category: "أنميات" },
  { word: "بلو لوك", category: "أنميات" }, { word: "هايكيو", category: "أنميات" },
  { word: "شينشان", category: "أنميات" }, { word: "اينوياشا", category: "أنميات" },
  { word: "دراغون بول", category: "أنميات" }, { word: "ون بيس", category: "أنميات" },
  { word: "يوغي يو", category: "أنميات" }, { word: "ديجيمون", category: "أنميات" },
  { word: "سايلور مون", category: "أنميات" }, { word: "غاندام", category: "أنميات" },
  { word: "بلاك كلوفر", category: "أنميات" }, { word: "طوكيو غول", category: "أنميات" },
  { word: "هجوم العمالقة", category: "أنميات" }, { word: "ديث نوت", category: "أنميات" },
  { word: "هنتر هنتر", category: "أنميات" }, { word: "فيري تيل", category: "أنميات" },
  { word: "قاتل الشياطين", category: "أنميات" }, { word: "جوجوتسو كايسن", category: "أنميات" },
  { word: "ون بانش مان", category: "أنميات" }, { word: "سباي فاميلي", category: "أنميات" },
  { word: "تشينسو مان", category: "أنميات" }, { word: "سورد ارت اونلاين", category: "أنميات" },
  { word: "شامان كينغ", category: "أنميات" }, { word: "ايفانجيليون", category: "أنميات" },
  { word: "بيرسيرك", category: "أنميات" }, { word: "هيرو اكاديميا", category: "أنميات" },
  { word: "بوروتو", category: "أنميات" }, { word: "طوكيو ريفنجرز", category: "أنميات" },
  { word: "فول ميتال الكيميست", category: "أنميات" }, { word: "كود غياس", category: "أنميات" },
  { word: "اوفرلورد", category: "أنميات" }, { word: "ري زيرو", category: "أنميات" },

  // ===================== مسلسلات (مسلسلات كويتية) =====================
  { word: "الفريج", category: "مسلسلات" }, { word: "وحوش", category: "مسلسلات" },
  { word: "ساق البامبو", category: "مسلسلات" }, { word: "دفعة القاهرة", category: "مسلسلات" },
  { word: "امينة حاف", category: "مسلسلات" }, { word: "امر اخلاء", category: "مسلسلات" },
  { word: "درب الزلق", category: "مسلسلات" }, { word: "خالتي قماشة", category: "مسلسلات" },
  { word: "رقية و سبيكة", category: "مسلسلات" }, { word: "الغرباء", category: "مسلسلات" },
  { word: "بدر الزمان", category: "مسلسلات" }, { word: "الابريق المكسور", category: "مسلسلات" },
  { word: "علاء الدين", category: "مسلسلات" }, { word: "خرج و لم يعد", category: "مسلسلات" },
  { word: "الاسوار", category: "مسلسلات" }, { word: "حبابة", category: "مسلسلات" },
  { word: "سليمان الطيب", category: "مسلسلات" }, { word: "بوهباش", category: "مسلسلات" },
  { word: "يوميات متقاعد", category: "مسلسلات" }, { word: "الملقوفة", category: "مسلسلات" },
  { word: "على الدنيا السلام", category: "مسلسلات" },

  // ===================== كرتون قديم =====================
  { word: "عدنان و لينا", category: "كرتون قديم" }, { word: "كبامارو", category: "كرتون قديم" },
  { word: "ماروكو", category: "كرتون قديم" }, { word: "هايدي", category: "كرتون قديم" },
  { word: "سالي", category: "كرتون قديم" }, { word: "كابتن ماجد", category: "كرتون قديم" },
  { word: "غوليفر", category: "كرتون قديم" }, { word: "سندريلا", category: "كرتون قديم" },
  { word: "بامبي", category: "كرتون قديم" }, { word: "بينوكيو", category: "كرتون قديم" },
  { word: "بوباي", category: "كرتون قديم" }, { word: "السنافر", category: "كرتون قديم" },
  { word: "توم و جيري", category: "كرتون قديم" }, { word: "ميكي ماوس", category: "كرتون قديم" },
  { word: "ليدي اوسكار", category: "كرتون قديم" }, { word: "الرحالة الصغير", category: "كرتون قديم" },
  { word: "غرندايزر", category: "كرتون قديم" }, { word: "عبقور", category: "كرتون قديم" },
  { word: "سنان", category: "كرتون قديم" }, { word: "زينة و نحول", category: "كرتون قديم" },
  { word: "ريمي", category: "كرتون قديم" }, { word: "ساندي بل", category: "كرتون قديم" },
  { word: "جورجي", category: "كرتون قديم" }, { word: "بابار", category: "كرتون قديم" },
  { word: "ماوكلي", category: "كرتون قديم" }, { word: "النمر الوردي", category: "كرتون قديم" },
  { word: "سلاحف النينجا", category: "كرتون قديم" }, { word: "عائلة فلينستون", category: "كرتون قديم" },
  { word: "سكوبي دو", category: "كرتون قديم" }, { word: "مغامرات نيلز", category: "كرتون قديم" },
  { word: "الاميرة ياقوت", category: "كرتون قديم" }, { word: "بسمة و عبدو", category: "كرتون قديم" },
  { word: "حكايات عالمية", category: "كرتون قديم" }, { word: "بيل و سبستيان", category: "كرتون قديم" },
  { word: "الليدي ليدي", category: "كرتون قديم" }, { word: "صاحب الظل الطويل", category: "كرتون قديم" },
  { word: "ابطال الملاعب", category: "كرتون قديم" },

  // ===================== أسماء =====================
  { word: "محمد", category: "أسماء" }, { word: "احمد", category: "أسماء" },
  { word: "خالد", category: "أسماء" }, { word: "سالم", category: "أسماء" },
  { word: "فهد", category: "أسماء" }, { word: "ناصر", category: "أسماء" },
  { word: "يوسف", category: "أسماء" }, { word: "عبدالله", category: "أسماء" },
  { word: "جابر", category: "أسماء" }, { word: "ابراهيم", category: "أسماء" },
  { word: "مريم", category: "أسماء" }, { word: "نورة", category: "أسماء" },
  { word: "سارة", category: "أسماء" }, { word: "هند", category: "أسماء" },
  { word: "موزة", category: "أسماء" }, { word: "شيخة", category: "أسماء" },
  { word: "خديجة", category: "أسماء" }, { word: "عائشة", category: "أسماء" },
  { word: "امل", category: "أسماء" }, { word: "ريم", category: "أسماء" },
  { word: "عبدالعزيز", category: "أسماء" }, { word: "عبدالرحمن", category: "أسماء" },
  { word: "سعود", category: "أسماء" }, { word: "فيصل", category: "أسماء" },
  { word: "طلال", category: "أسماء" }, { word: "بدر", category: "أسماء" },
  { word: "راشد", category: "أسماء" }, { word: "وليد", category: "أسماء" },
  { word: "عمر", category: "أسماء" }, { word: "علي", category: "أسماء" },
  { word: "حسين", category: "أسماء" }, { word: "حسن", category: "أسماء" },
  { word: "تركي", category: "أسماء" }, { word: "جاسم", category: "أسماء" },
  { word: "فارس", category: "أسماء" }, { word: "لطيفة", category: "أسماء" },
  { word: "فاطمة", category: "أسماء" }, { word: "عزيزة", category: "أسماء" },
  { word: "بدرية", category: "أسماء" }, { word: "منيرة", category: "أسماء" },
  { word: "دلال", category: "أسماء" }, { word: "هيا", category: "أسماء" },
  { word: "رهف", category: "أسماء" }, { word: "لمى", category: "أسماء" },
  { word: "جود", category: "أسماء" }, { word: "نوف", category: "أسماء" },
  { word: "شهد", category: "أسماء" }, { word: "جنى", category: "أسماء" },
  { word: "لولوة", category: "أسماء" }, { word: "مها", category: "أسماء" },

  // ===================== مسرحيات (مسرحيات كويتية قديمة) =====================
  { word: "عزوبي السالمية", category: "مسرحيات" }, { word: "باي باي لندن", category: "مسرحيات" },
  { word: "استارثوني و انا حي", category: "مسرحيات" }, { word: "على هامان يا فرعون", category: "مسرحيات" },
  { word: "بني صامت", category: "مسرحيات" }, { word: "سيف العرب", category: "مسرحيات" },
  { word: "باي باي عرب", category: "مسرحيات" }, { word: "حط الطير طار الطير", category: "مسرحيات" },
  { word: "فرحة امة", category: "مسرحيات" }, { word: "اسلام عمر", category: "مسرحيات" },
  { word: "حرب البسوس", category: "مسرحيات" }, { word: "فتح الاندلس", category: "مسرحيات" },
  { word: "صقر قريش", category: "مسرحيات" },

  // ===================== روايات (من سلسلة روائع الأدب العالمي) =====================
  { word: "مغامرات السندباد البحري", category: "روايات" }, { word: "رحلات جوليفر", category: "روايات" },
  { word: "مزرعة الحيوان", category: "روايات" }, { word: "جزيرة الكنز", category: "روايات" },
  { word: "روبنسون كروزو", category: "روايات" }, { word: "روبن هود", category: "روايات" },
  { word: "دراكولا", category: "روايات" }, { word: "فرانكنشتاين", category: "روايات" },
  { word: "موبي ديك", category: "روايات" }, { word: "الامير الصغير", category: "روايات" },
  { word: "كوخ العم توم", category: "روايات" }, { word: "ثلاثة رجال في قارب", category: "روايات" },
  { word: "اللؤلؤة", category: "روايات" }, { word: "عناقيد الغضب", category: "روايات" },
  { word: "روميو و جولييت", category: "روايات" }, { word: "مكبث", category: "روايات" },
  { word: "عطيل", category: "روايات" }, { word: "الملك لير", category: "روايات" },
  { word: "هملت", category: "روايات" }, { word: "الشيخ و البحر", category: "روايات" },
  { word: "وداعا للسلاح", category: "روايات" }, { word: "اليس في بلاد العجائب", category: "روايات" },
  { word: "مونتي كريستو", category: "روايات" }, { word: "الفرسان الثلاثة", category: "روايات" },
  { word: "اوليفر تويست", category: "روايات" }, { word: "توم سوير", category: "روايات" },
  { word: "مغامرات هاكلبري فين", category: "روايات" }, { word: "جين اير", category: "روايات" },
  { word: "كبرياء و هوى", category: "روايات" }, { word: "ذهب مع الريح", category: "روايات" },
  { word: "الاخوة كارامازوف", category: "روايات" }, { word: "انا كارنينا", category: "روايات" },
  { word: "مغامرات شيرلوك هولمز", category: "روايات" }, { word: "دموع التماسيح", category: "روايات" },
  { word: "قصة مدينتين", category: "روايات" }, { word: "مرتفعات وذرينغ", category: "روايات" },
  { word: "الامير و الفقير", category: "روايات" }, { word: "اوقات صعبة", category: "روايات" },
  { word: "السهم الاسود", category: "روايات" }, { word: "كنوز الملك سليمان", category: "روايات" },
  { word: "نداء البراري", category: "روايات" }, { word: "نزل جامايكا", category: "روايات" },
  { word: "الحديقة السرية", category: "روايات" }, { word: "رجل من غلاسكو", category: "روايات" },

  // ===================== رياضة =====================
  { word: "كرة قدم", category: "رياضة" }, { word: "سباحة", category: "رياضة" },
  { word: "كرة سلة", category: "رياضة" }, { word: "تنس", category: "رياضة" },
  { word: "جري", category: "رياضة" }, { word: "ملاكمة", category: "رياضة" },
  { word: "جمباز", category: "رياضة" }, { word: "كرة طائرة", category: "رياضة" },
  { word: "جودو", category: "رياضة" }, { word: "كاراتيه", category: "رياضة" },
  { word: "هوكي", category: "رياضة" }, { word: "اسكواش", category: "رياضة" },
  { word: "مصارعة", category: "رياضة" }, { word: "دراجات", category: "رياضة" },
  { word: "غطس", category: "رياضة" }, { word: "جولف", category: "رياضة" },
  { word: "كرة يد", category: "رياضة" }, { word: "تايكوندو", category: "رياضة" },
  { word: "رفع اثقال", category: "رياضة" }, { word: "مبارزة", category: "رياضة" },
  { word: "رماية", category: "رياضة" }, { word: "تجديف", category: "رياضة" },
  { word: "ركوب خيل", category: "رياضة" }, { word: "بولينج", category: "رياضة" },
  { word: "بلياردو", category: "رياضة" }, { word: "كرلنغ", category: "رياضة" },
  { word: "تزلج", category: "رياضة" }, { word: "قفز", category: "رياضة" },
  { word: "وثب طويل", category: "رياضة" }, { word: "رمي جلة", category: "رياضة" },
  { word: "رمي رمح", category: "رياضة" }, { word: "شطرنج", category: "رياضة" },
  { word: "سباق", category: "رياضة" },

  // ===================== ألوان =====================
  { word: "ازرق", category: "ألوان" }, { word: "احمر", category: "ألوان" },
  { word: "اخضر", category: "ألوان" }, { word: "اصفر", category: "ألوان" },
  { word: "اسود", category: "ألوان" }, { word: "ابيض", category: "ألوان" },
  { word: "بنفسجي", category: "ألوان" }, { word: "وردي", category: "ألوان" },
  { word: "برتقالي", category: "ألوان" }, { word: "بني", category: "ألوان" },
  { word: "رمادي", category: "ألوان" }, { word: "ذهبي", category: "ألوان" },
  { word: "فضي", category: "ألوان" }, { word: "فيروزي", category: "ألوان" },
  { word: "تركواز", category: "ألوان" }, { word: "كحلي", category: "ألوان" },
  { word: "بيج", category: "ألوان" }, { word: "عنابي", category: "ألوان" },
  { word: "سماوي", category: "ألوان" }, { word: "نيلي", category: "ألوان" },
  { word: "زهري", category: "ألوان" }, { word: "خمري", category: "ألوان" },
  { word: "زيتي", category: "ألوان" }, { word: "ياقوتي", category: "ألوان" },
  { word: "قرمزي", category: "ألوان" }, { word: "ارجواني", category: "ألوان" },
  { word: "كريمي", category: "ألوان" }, { word: "رصاصي", category: "ألوان" },
  { word: "لؤلؤي", category: "ألوان" }, { word: "مرجاني", category: "ألوان" },
  { word: "ليموني", category: "ألوان" }, { word: "برونزي", category: "ألوان" },
  { word: "نحاسي", category: "ألوان" }, { word: "موف", category: "ألوان" },
  { word: "عاجي", category: "ألوان" },

  // ===================== مناطق الكويت =====================
  { word: "السرة", category: "مناطق الكويت" }, { word: "الجابرية", category: "مناطق الكويت" },
  { word: "فنيطيس", category: "مناطق الكويت" }, { word: "سلوى", category: "مناطق الكويت" },
  { word: "السالمية", category: "مناطق الكويت" }, { word: "حولي", category: "مناطق الكويت" },
  { word: "الفروانية", category: "مناطق الكويت" }, { word: "الجهراء", category: "مناطق الكويت" },
  { word: "بيان", category: "مناطق الكويت" }, { word: "الرميثية", category: "مناطق الكويت" },
  { word: "اليرموك", category: "مناطق الكويت" }, { word: "قرطبة", category: "مناطق الكويت" },
  { word: "الشامية", category: "مناطق الكويت" }, { word: "كيفان", category: "مناطق الكويت" },
  { word: "الدسمة", category: "مناطق الكويت" }, { word: "الروضة", category: "مناطق الكويت" },
  { word: "القادسية", category: "مناطق الكويت" }, { word: "خيطان", category: "مناطق الكويت" },
  { word: "دسمان", category: "مناطق الكويت" }, { word: "الشرق", category: "مناطق الكويت" },
  { word: "الصوابر", category: "مناطق الكويت" }, { word: "المرقاب", category: "مناطق الكويت" },
  { word: "القبلة", category: "مناطق الكويت" }, { word: "الصالحية", category: "مناطق الكويت" },
  { word: "الوطية", category: "مناطق الكويت" }, { word: "المنصورية", category: "مناطق الكويت" },
  { word: "العديلية", category: "مناطق الكويت" }, { word: "النزهة", category: "مناطق الكويت" },
  { word: "الدوحة", category: "مناطق الكويت" }, { word: "الخالدية", category: "مناطق الكويت" },
  { word: "الفيحاء", category: "مناطق الكويت" }, { word: "الدعية", category: "مناطق الكويت" },
  { word: "الصليبيخات", category: "مناطق الكويت" }, { word: "غرناطة", category: "مناطق الكويت" },
  { word: "جابر الاحمد", category: "مناطق الكويت" }, { word: "عبدالله السالم", category: "مناطق الكويت" },
  { word: "القيروان", category: "مناطق الكويت" }, { word: "النهضة", category: "مناطق الكويت" },
  { word: "بنيد القار", category: "مناطق الكويت" }, { word: "الشويخ", category: "مناطق الكويت" },
  { word: "مشرف", category: "مناطق الكويت" }, { word: "الشعب", category: "مناطق الكويت" },
  { word: "السلام", category: "مناطق الكويت" }, { word: "حطين", category: "مناطق الكويت" },
  { word: "الزهراء", category: "مناطق الكويت" }, { word: "مبارك العبدالله", category: "مناطق الكويت" },
  { word: "الشهداء", category: "مناطق الكويت" }, { word: "البدع", category: "مناطق الكويت" },
  { word: "الصديق", category: "مناطق الكويت" }, { word: "النقرة", category: "مناطق الكويت" },
  { word: "الاندلس", category: "مناطق الكويت" }, { word: "اشبيلية", category: "مناطق الكويت" },
  { word: "ابرق خيطان", category: "مناطق الكويت" }, { word: "العارضية", category: "مناطق الكويت" },
  { word: "الفردوس", category: "مناطق الكويت" }, { word: "صباح الناصر", category: "مناطق الكويت" },
  { word: "عبدالله المبارك", category: "مناطق الكويت" }, { word: "الضجيج", category: "مناطق الكويت" },
  { word: "الشدادية", category: "مناطق الكويت" }, { word: "العمرية", category: "مناطق الكويت" },
  { word: "الرابية", category: "مناطق الكويت" }, { word: "الرحاب", category: "مناطق الكويت" },
  { word: "الرقعي", category: "مناطق الكويت" }, { word: "جليب الشيوخ", category: "مناطق الكويت" },
  { word: "الواحة", category: "مناطق الكويت" }, { word: "العيون", category: "مناطق الكويت" },
  { word: "القصر", category: "مناطق الكويت" }, { word: "النسيم", category: "مناطق الكويت" },
  { word: "تيماء", category: "مناطق الكويت" }, { word: "النعيم", category: "مناطق الكويت" },
  { word: "سعد العبدالله", category: "مناطق الكويت" }, { word: "كاظمة", category: "مناطق الكويت" },
  { word: "الروضتين", category: "مناطق الكويت" }, { word: "ام العيش", category: "مناطق الكويت" },
  { word: "السالمي", category: "مناطق الكويت" }, { word: "كبد", category: "مناطق الكويت" },
  { word: "الصليبية", category: "مناطق الكويت" }, { word: "امغرة", category: "مناطق الكويت" },
  { word: "خباري العوازم", category: "مناطق الكويت" }, { word: "الصبية", category: "مناطق الكويت" },
  { word: "المطلاع", category: "مناطق الكويت" }, { word: "العبدلي", category: "مناطق الكويت" },
  { word: "بوبيان", category: "مناطق الكويت" }, { word: "وربة", category: "مناطق الكويت" },
  { word: "صباح السالم", category: "مناطق الكويت" }, { word: "المسيلة", category: "مناطق الكويت" },
  { word: "العدان", category: "مناطق الكويت" }, { word: "القصور", category: "مناطق الكويت" },
  { word: "القرين", category: "مناطق الكويت" }, { word: "الوسطى", category: "مناطق الكويت" },
  { word: "صبحان", category: "مناطق الكويت" },
  // ===================== سيارات =====================
  { word: "تويوتا", category: "سيارات" }, { word: "لكزس", category: "سيارات" },
  { word: "مرسيدس", category: "سيارات" }, { word: "بي ام دبليو", category: "سيارات" },
  { word: "فورد", category: "سيارات" }, { word: "شيفروليه", category: "سيارات" },
  { word: "نيسان", category: "سيارات" }, { word: "هوندا", category: "سيارات" },
  { word: "فيراري", category: "سيارات" }, { word: "لامبورغيني", category: "سيارات" },
  { word: "بورش", category: "سيارات" }, { word: "لاند روفر", category: "سيارات" },
  { word: "جيب", category: "سيارات" }, { word: "اودي", category: "سيارات" },
  { word: "فولكس فاجن", category: "سيارات" }, { word: "هيونداي", category: "سيارات" },
  { word: "كيا", category: "سيارات" }, { word: "مازدا", category: "سيارات" },
  { word: "سوزوكي", category: "سيارات" }, { word: "ميتسوبيشي", category: "سيارات" },
  { word: "رينو", category: "سيارات" }, { word: "بيجو", category: "سيارات" },
  { word: "فيات", category: "سيارات" }, { word: "فولفو", category: "سيارات" },
  { word: "جاكوار", category: "سيارات" }, { word: "بنتلي", category: "سيارات" },
  { word: "رولز رويس", category: "سيارات" }, { word: "استون مارتن", category: "سيارات" },
  { word: "بوغاتي", category: "سيارات" }, { word: "مازيراتي", category: "سيارات" },
  { word: "الفا روميو", category: "سيارات" }, { word: "سوبارو", category: "سيارات" },
  { word: "انفينيتي", category: "سيارات" }, { word: "جينيسيس", category: "سيارات" },
  { word: "جي ام سي", category: "سيارات" }, { word: "كاديلاك", category: "سيارات" },
  { word: "لينكولن", category: "سيارات" }, { word: "كرايسلر", category: "سيارات" },
  { word: "دودج", category: "سيارات" }, { word: "بويك", category: "سيارات" },
  { word: "ميني", category: "سيارات" }, { word: "سكودا", category: "سيارات" },
  { word: "سيات", category: "سيارات" }, { word: "اوبل", category: "سيارات" },
  { word: "سيتروين", category: "سيارات" }, { word: "داسيا", category: "سيارات" },
  { word: "تسلا", category: "سيارات" }, { word: "هامر", category: "سيارات" },
  { word: "سمارت", category: "سيارات" }, { word: "ايسوزو", category: "سيارات" },
  { word: "تاتا", category: "سيارات" }, { word: "شيري", category: "سيارات" },
  { word: "جيلي", category: "سيارات" }, { word: "لوتس", category: "سيارات" },
  { word: "مكلارين", category: "سيارات" }, { word: "بونتياك", category: "سيارات" },
  { word: "ساب", category: "سيارات" }, { word: "دايهاتسو", category: "سيارات" },

  // ===================== أندية كرة قدم عالمية =====================
  { word: "ريال مدريد", category: "أندية كرة قدم عالمية" }, { word: "برشلونة", category: "أندية كرة قدم عالمية" },
  { word: "اتلتيكو مدريد", category: "أندية كرة قدم عالمية" }, { word: "مانشستر يونايتد", category: "أندية كرة قدم عالمية" },
  { word: "مانشستر سيتي", category: "أندية كرة قدم عالمية" }, { word: "ليفربول", category: "أندية كرة قدم عالمية" },
  { word: "تشيلسي", category: "أندية كرة قدم عالمية" }, { word: "ارسنال", category: "أندية كرة قدم عالمية" },
  { word: "توتنهام", category: "أندية كرة قدم عالمية" }, { word: "بايرن ميونخ", category: "أندية كرة قدم عالمية" },
  { word: "بروسيا دورتموند", category: "أندية كرة قدم عالمية" }, { word: "يوفنتوس", category: "أندية كرة قدم عالمية" },
  { word: "ميلان", category: "أندية كرة قدم عالمية" }, { word: "انتر ميلان", category: "أندية كرة قدم عالمية" },
  { word: "نابولي", category: "أندية كرة قدم عالمية" }, { word: "روما", category: "أندية كرة قدم عالمية" },
  { word: "باريس سان جيرمان", category: "أندية كرة قدم عالمية" }, { word: "اياكس امستردام", category: "أندية كرة قدم عالمية" },
  { word: "بورتو", category: "أندية كرة قدم عالمية" }, { word: "بنفيكا", category: "أندية كرة قدم عالمية" },
  { word: "سبورتنج لشبونة", category: "أندية كرة قدم عالمية" }, { word: "بوكا جونيورز", category: "أندية كرة قدم عالمية" },
  { word: "ريفر بليت", category: "أندية كرة قدم عالمية" }, { word: "فلامنغو", category: "أندية كرة قدم عالمية" },
  { word: "بالميراس", category: "أندية كرة قدم عالمية" }, { word: "سانتوس", category: "أندية كرة قدم عالمية" },
  { word: "كورينثيانس", category: "أندية كرة قدم عالمية" }, { word: "الهلال", category: "أندية كرة قدم عالمية" },
  { word: "النصر", category: "أندية كرة قدم عالمية" }, { word: "الاتحاد", category: "أندية كرة قدم عالمية" },
  { word: "الاهلي", category: "أندية كرة قدم عالمية" }, { word: "الزمالك", category: "أندية كرة قدم عالمية" },
  { word: "وست هام", category: "أندية كرة قدم عالمية" }, { word: "ليستر سيتي", category: "أندية كرة قدم عالمية" },
  { word: "نيوكاسل يونايتد", category: "أندية كرة قدم عالمية" }, { word: "استون فيلا", category: "أندية كرة قدم عالمية" },
  { word: "فالنسيا", category: "أندية كرة قدم عالمية" }, { word: "فياريال", category: "أندية كرة قدم عالمية" },
  { word: "بيتيس", category: "أندية كرة قدم عالمية" }, { word: "لايبزيغ", category: "أندية كرة قدم عالمية" },
  { word: "باير ليفركوزن", category: "أندية كرة قدم عالمية" }, { word: "شالكه", category: "أندية كرة قدم عالمية" },
  { word: "فينورد", category: "أندية كرة قدم عالمية" }, { word: "سلتيك", category: "أندية كرة قدم عالمية" },
  { word: "رينجرز", category: "أندية كرة قدم عالمية" }, { word: "غلطة سراي", category: "أندية كرة قدم عالمية" },
  { word: "فنربخشة", category: "أندية كرة قدم عالمية" }, { word: "بشيكتاش", category: "أندية كرة قدم عالمية" },

  // ===================== لاعبين كرة قدم =====================
  { word: "ميسي", category: "لاعبين كرة قدم" }, { word: "رونالدو", category: "لاعبين كرة قدم" },
  { word: "نيمار", category: "لاعبين كرة قدم" }, { word: "مبابي", category: "لاعبين كرة قدم" },
  { word: "بيليه", category: "لاعبين كرة قدم" }, { word: "مارادونا", category: "لاعبين كرة قدم" },
  { word: "زيدان", category: "لاعبين كرة قدم" }, { word: "رونالدينيو", category: "لاعبين كرة قدم" },
  { word: "بيكهام", category: "لاعبين كرة قدم" }, { word: "مودريتش", category: "لاعبين كرة قدم" },
  { word: "صلاح", category: "لاعبين كرة قدم" }, { word: "بنزيما", category: "لاعبين كرة قدم" },
  { word: "سواريز", category: "لاعبين كرة قدم" }, { word: "اينيستا", category: "لاعبين كرة قدم" },
  { word: "تشافي", category: "لاعبين كرة قدم" }, { word: "بوفون", category: "لاعبين كرة قدم" },
  { word: "كاسياس", category: "لاعبين كرة قدم" }, { word: "راموس", category: "لاعبين كرة قدم" },
  { word: "بوسكيتس", category: "لاعبين كرة قدم" }, { word: "بيكيه", category: "لاعبين كرة قدم" },
  { word: "فان دايك", category: "لاعبين كرة قدم" }, { word: "دي بروين", category: "لاعبين كرة قدم" },
  { word: "كروس", category: "لاعبين كرة قدم" }, { word: "نوير", category: "لاعبين كرة قدم" },
  { word: "ليفاندوفسكي", category: "لاعبين كرة قدم" }, { word: "هالاند", category: "لاعبين كرة قدم" },
  { word: "فينيسيوس", category: "لاعبين كرة قدم" }, { word: "رودريغو", category: "لاعبين كرة قدم" },
  { word: "بيدري", category: "لاعبين كرة قدم" }, { word: "غافي", category: "لاعبين كرة قدم" },
  { word: "هازارد", category: "لاعبين كرة قدم" }, { word: "اوباميانغ", category: "لاعبين كرة قدم" },
  { word: "ساديو ماني", category: "لاعبين كرة قدم" }, { word: "محرز", category: "لاعبين كرة قدم" },
  { word: "كين", category: "لاعبين كرة قدم" }, { word: "فودين", category: "لاعبين كرة قدم" },
  { word: "بيلينغهام", category: "لاعبين كرة قدم" }, { word: "كامافينغا", category: "لاعبين كرة قدم" },
  { word: "بوغبا", category: "لاعبين كرة قدم" }, { word: "كانتي", category: "لاعبين كرة قدم" },
  { word: "جريزمان", category: "لاعبين كرة قدم" }, { word: "كوتينيو", category: "لاعبين كرة قدم" },
  { word: "اجويرو", category: "لاعبين كرة قدم" }, { word: "ديماريا", category: "لاعبين كرة قدم" },
  { word: "بالوتيلي", category: "لاعبين كرة قدم" }, { word: "توتي", category: "لاعبين كرة قدم" },
  { word: "ديل بييرو", category: "لاعبين كرة قدم" }, { word: "مالديني", category: "لاعبين كرة قدم" },
  { word: "فيغو", category: "لاعبين كرة قدم" }, { word: "كافو", category: "لاعبين كرة قدم" },
  { word: "روبرتو كارلوس", category: "لاعبين كرة قدم" }, { word: "كاكا", category: "لاعبين كرة قدم" },
  { word: "كلوزه", category: "لاعبين كرة قدم" }, { word: "بالاك", category: "لاعبين كرة قدم" },
  { word: "تيري", category: "لاعبين كرة قدم" }, { word: "لامبارد", category: "لاعبين كرة قدم" },
  { word: "جيرارد", category: "لاعبين كرة قدم" },

  // ===================== سور القرآن الكريم (فئة حصرية) =====================
  { word: "الفاتحة", category: "سور القرآن الكريم" }, { word: "البقرة", category: "سور القرآن الكريم" },
  { word: "ال عمران", category: "سور القرآن الكريم" }, { word: "النساء", category: "سور القرآن الكريم" },
  { word: "المائدة", category: "سور القرآن الكريم" }, { word: "الانعام", category: "سور القرآن الكريم" },
  { word: "الاعراف", category: "سور القرآن الكريم" }, { word: "الانفال", category: "سور القرآن الكريم" },
  { word: "التوبة", category: "سور القرآن الكريم" }, { word: "يونس", category: "سور القرآن الكريم" },
  { word: "هود", category: "سور القرآن الكريم" }, { word: "يوسف", category: "سور القرآن الكريم" },
  { word: "الرعد", category: "سور القرآن الكريم" }, { word: "ابراهيم", category: "سور القرآن الكريم" },
  { word: "الحجر", category: "سور القرآن الكريم" }, { word: "النحل", category: "سور القرآن الكريم" },
  { word: "الاسراء", category: "سور القرآن الكريم" }, { word: "الكهف", category: "سور القرآن الكريم" },
  { word: "مريم", category: "سور القرآن الكريم" }, { word: "الانبياء", category: "سور القرآن الكريم" },
  { word: "الحج", category: "سور القرآن الكريم" }, { word: "المؤمنون", category: "سور القرآن الكريم" },
  { word: "النور", category: "سور القرآن الكريم" }, { word: "الفرقان", category: "سور القرآن الكريم" },
  { word: "الشعراء", category: "سور القرآن الكريم" }, { word: "النمل", category: "سور القرآن الكريم" },
  { word: "القصص", category: "سور القرآن الكريم" }, { word: "العنكبوت", category: "سور القرآن الكريم" },
  { word: "الروم", category: "سور القرآن الكريم" }, { word: "لقمان", category: "سور القرآن الكريم" },
  { word: "السجدة", category: "سور القرآن الكريم" }, { word: "الاحزاب", category: "سور القرآن الكريم" },
  { word: "سبا", category: "سور القرآن الكريم" }, { word: "فاطر", category: "سور القرآن الكريم" },
  { word: "الصافات", category: "سور القرآن الكريم" }, { word: "الزمر", category: "سور القرآن الكريم" },
  { word: "غافر", category: "سور القرآن الكريم" }, { word: "فصلت", category: "سور القرآن الكريم" },
  { word: "الشورى", category: "سور القرآن الكريم" }, { word: "الزخرف", category: "سور القرآن الكريم" },
  { word: "الدخان", category: "سور القرآن الكريم" }, { word: "الجاثية", category: "سور القرآن الكريم" },
  { word: "الاحقاف", category: "سور القرآن الكريم" }, { word: "محمد", category: "سور القرآن الكريم" },
  { word: "الفتح", category: "سور القرآن الكريم" }, { word: "الحجرات", category: "سور القرآن الكريم" },
  { word: "الذاريات", category: "سور القرآن الكريم" }, { word: "الطور", category: "سور القرآن الكريم" },
  { word: "النجم", category: "سور القرآن الكريم" }, { word: "القمر", category: "سور القرآن الكريم" },
  { word: "الرحمن", category: "سور القرآن الكريم" }, { word: "الواقعة", category: "سور القرآن الكريم" },
  { word: "الحديد", category: "سور القرآن الكريم" }, { word: "المجادلة", category: "سور القرآن الكريم" },
  { word: "الحشر", category: "سور القرآن الكريم" }, { word: "الممتحنة", category: "سور القرآن الكريم" },
  { word: "الصف", category: "سور القرآن الكريم" }, { word: "الجمعة", category: "سور القرآن الكريم" },
  { word: "المنافقون", category: "سور القرآن الكريم" }, { word: "التغابن", category: "سور القرآن الكريم" },
  { word: "الطلاق", category: "سور القرآن الكريم" }, { word: "التحريم", category: "سور القرآن الكريم" },
  { word: "الملك", category: "سور القرآن الكريم" }, { word: "القلم", category: "سور القرآن الكريم" },
  { word: "الحاقة", category: "سور القرآن الكريم" }, { word: "المعارج", category: "سور القرآن الكريم" },
  { word: "نوح", category: "سور القرآن الكريم" }, { word: "الجن", category: "سور القرآن الكريم" },
  { word: "المزمل", category: "سور القرآن الكريم" }, { word: "المدثر", category: "سور القرآن الكريم" },
  { word: "القيامة", category: "سور القرآن الكريم" }, { word: "الانسان", category: "سور القرآن الكريم" },
  { word: "المرسلات", category: "سور القرآن الكريم" }, { word: "النبا", category: "سور القرآن الكريم" },
  { word: "النازعات", category: "سور القرآن الكريم" }, { word: "عبس", category: "سور القرآن الكريم" },
  { word: "التكوير", category: "سور القرآن الكريم" }, { word: "الانفطار", category: "سور القرآن الكريم" },
  { word: "المطففين", category: "سور القرآن الكريم" }, { word: "الانشقاق", category: "سور القرآن الكريم" },
  { word: "البروج", category: "سور القرآن الكريم" }, { word: "الطارق", category: "سور القرآن الكريم" },
  { word: "الاعلى", category: "سور القرآن الكريم" }, { word: "الغاشية", category: "سور القرآن الكريم" },
  { word: "الفجر", category: "سور القرآن الكريم" }, { word: "البلد", category: "سور القرآن الكريم" },
  { word: "الشمس", category: "سور القرآن الكريم" }, { word: "الليل", category: "سور القرآن الكريم" },
  { word: "الضحى", category: "سور القرآن الكريم" }, { word: "الشرح", category: "سور القرآن الكريم" },
  { word: "التين", category: "سور القرآن الكريم" }, { word: "العلق", category: "سور القرآن الكريم" },
  { word: "القدر", category: "سور القرآن الكريم" }, { word: "البينة", category: "سور القرآن الكريم" },
  { word: "الزلزلة", category: "سور القرآن الكريم" }, { word: "العاديات", category: "سور القرآن الكريم" },
  { word: "القارعة", category: "سور القرآن الكريم" }, { word: "التكاثر", category: "سور القرآن الكريم" },
  { word: "العصر", category: "سور القرآن الكريم" }, { word: "الهمزة", category: "سور القرآن الكريم" },
  { word: "الفيل", category: "سور القرآن الكريم" }, { word: "قريش", category: "سور القرآن الكريم" },
  { word: "الماعون", category: "سور القرآن الكريم" }, { word: "الكوثر", category: "سور القرآن الكريم" },
  { word: "الكافرون", category: "سور القرآن الكريم" }, { word: "النصر", category: "سور القرآن الكريم" },
  { word: "المسد", category: "سور القرآن الكريم" }, { word: "الاخلاص", category: "سور القرآن الكريم" },
  { word: "الفلق", category: "سور القرآن الكريم" }, { word: "الناس", category: "سور القرآن الكريم" },

];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { WORDS };
}
