// بنك الكلمات للعبة "احزر الكلمة" - كل كلمة عربية فصحى بدون تشكيل، مع فئة تستخدم في زر التلميح
// طول الكلمات يتراوح بين 3 و21 حرفاً (العناوين متعددة الكلمات مفصولة بمسافة) ويُختار عشوائياً عند بدء كل جولة

const WORDS = [
  // ===================== دولة =====================
  { word: "مصر", category: "دولة" }, { word: "قطر", category: "دولة" },
  { word: "عمان", category: "دولة" }, { word: "تونس", category: "دولة" },
  { word: "ليبيا", category: "دولة" }, { word: "سوريا", category: "دولة" },
  { word: "اليمن", category: "دولة" }, { word: "لبنان", category: "دولة" },
  { word: "الهند", category: "دولة" }, { word: "الصين", category: "دولة" },
  { word: "العراق", category: "دولة" }, { word: "المغرب", category: "دولة" },
  { word: "الاردن", category: "دولة" }, { word: "السودان", category: "دولة" },
  { word: "الجزائر", category: "دولة" }, { word: "البحرين", category: "دولة" },
  { word: "الصومال", category: "دولة" }, { word: "السعودية", category: "دولة" },
  { word: "فرنسا", category: "دولة" }, { word: "اسبانيا", category: "دولة" },
  { word: "ايطاليا", category: "دولة" }, { word: "المانيا", category: "دولة" },
  { word: "بريطانيا", category: "دولة" }, { word: "اليابان", category: "دولة" },
  { word: "كوريا", category: "دولة" }, { word: "تركيا", category: "دولة" },
  { word: "اليونان", category: "دولة" }, { word: "روسيا", category: "دولة" },
  { word: "امريكا", category: "دولة" }, { word: "كندا", category: "دولة" },
  { word: "البرازيل", category: "دولة" }, { word: "الارجنتين", category: "دولة" },
  { word: "نيجيريا", category: "دولة" }, { word: "كينيا", category: "دولة" },
  { word: "اثيوبيا", category: "دولة" }, { word: "غانا", category: "دولة" },
  { word: "فلسطين", category: "دولة" }, { word: "باكستان", category: "دولة" },
  { word: "ايران", category: "دولة" }, { word: "ماليزيا", category: "دولة" },
  { word: "اندونيسيا", category: "دولة" }, { word: "تايلاند", category: "دولة" },
  { word: "الفلبين", category: "دولة" }, { word: "استراليا", category: "دولة" },
  { word: "النمسا", category: "دولة" }, { word: "سويسرا", category: "دولة" },
  { word: "هولندا", category: "دولة" }, { word: "البرتغال", category: "دولة" },

  // ===================== تاريخ =====================
  { word: "حرب", category: "تاريخ" }, { word: "فتح", category: "تاريخ" },
  { word: "غزو", category: "تاريخ" }, { word: "عصر", category: "تاريخ" },
  { word: "قرن", category: "تاريخ" }, { word: "زمن", category: "تاريخ" },
  { word: "ثورة", category: "تاريخ" }, { word: "معركة", category: "تاريخ" },
  { word: "حضارة", category: "تاريخ" }, { word: "وثيقة", category: "تاريخ" },
  { word: "تحرير", category: "تاريخ" }, { word: "مملكة", category: "تاريخ" },
  { word: "خلافة", category: "تاريخ" }, { word: "معاهدة", category: "تاريخ" },
  { word: "احتلال", category: "تاريخ" }, { word: "استقلال", category: "تاريخ" },
  { word: "استعمار", category: "تاريخ" }, { word: "امبراطورية", category: "تاريخ" },
  { word: "جيش", category: "تاريخ" }, { word: "سلاح", category: "تاريخ" },
  { word: "قصر", category: "تاريخ" }, { word: "تاج", category: "تاريخ" },
  { word: "عرش", category: "تاريخ" }, { word: "وزير", category: "تاريخ" },
  { word: "امير", category: "تاريخ" }, { word: "سلطنة", category: "تاريخ" },
  { word: "امارة", category: "تاريخ" }, { word: "دستور", category: "تاريخ" },
  { word: "برلمان", category: "تاريخ" }, { word: "انقلاب", category: "تاريخ" },
  { word: "هدنة", category: "تاريخ" }, { word: "حصار", category: "تاريخ" },
  { word: "غزوة", category: "تاريخ" }, { word: "فتوحات", category: "تاريخ" },
  { word: "اثار", category: "تاريخ" }, { word: "متحف", category: "تاريخ" },
  { word: "تراث", category: "تاريخ" },

  // ===================== حيوان =====================
  { word: "اسد", category: "حيوان" }, { word: "نمر", category: "حيوان" },
  { word: "ذئب", category: "حيوان" }, { word: "فيل", category: "حيوان" },
  { word: "جمل", category: "حيوان" }, { word: "قرد", category: "حيوان" },
  { word: "نسر", category: "حيوان" }, { word: "صقر", category: "حيوان" },
  { word: "حوت", category: "حيوان" }, { word: "قطة", category: "حيوان" },
  { word: "كلب", category: "حيوان" }, { word: "حصان", category: "حيوان" },
  { word: "ارنب", category: "حيوان" }, { word: "ثعلب", category: "حيوان" },
  { word: "خروف", category: "حيوان" }, { word: "غزال", category: "حيوان" },
  { word: "بومة", category: "حيوان" }, { word: "زرافة", category: "حيوان" },
  { word: "تمساح", category: "حيوان" }, { word: "فراشة", category: "حيوان" },
  { word: "عصفور", category: "حيوان" }, { word: "حمامة", category: "حيوان" },
  { word: "دجاجة", category: "حيوان" }, { word: "عنكبوت", category: "حيوان" },
  { word: "باندا", category: "حيوان" }, { word: "كنغر", category: "حيوان" },
  { word: "دب", category: "حيوان" }, { word: "سلحفاة", category: "حيوان" },
  { word: "ضفدع", category: "حيوان" }, { word: "حرباء", category: "حيوان" },
  { word: "بجعة", category: "حيوان" }, { word: "بطة", category: "حيوان" },
  { word: "ديك", category: "حيوان" }, { word: "خفاش", category: "حيوان" },
  { word: "قنفذ", category: "حيوان" }, { word: "حلزون", category: "حيوان" },
  { word: "نحلة", category: "حيوان" }, { word: "دبور", category: "حيوان" },
  { word: "جراد", category: "حيوان" }, { word: "اخطبوط", category: "حيوان" },
  { word: "دولفين", category: "حيوان" }, { word: "قرش", category: "حيوان" },
  { word: "حمار", category: "حيوان" }, { word: "بغل", category: "حيوان" },
  { word: "ماعز", category: "حيوان" }, { word: "خنزير", category: "حيوان" },

  // ===================== طعام =====================
  { word: "خبز", category: "طعام" }, { word: "تمر", category: "طعام" },
  { word: "ارز", category: "طعام" }, { word: "لحم", category: "طعام" },
  { word: "سمك", category: "طعام" }, { word: "عسل", category: "طعام" },
  { word: "موز", category: "طعام" }, { word: "شاي", category: "طعام" },
  { word: "جبن", category: "طعام" }, { word: "سكر", category: "طعام" },
  { word: "ملح", category: "طعام" }, { word: "زيت", category: "طعام" },
  { word: "خيار", category: "طعام" }, { word: "زبدة", category: "طعام" },
  { word: "حليب", category: "طعام" }, { word: "قهوة", category: "طعام" },
  { word: "عصير", category: "طعام" }, { word: "تفاح", category: "طعام" },
  { word: "فطور", category: "طعام" }, { word: "خيارة", category: "طعام" },
  { word: "فاكهة", category: "طعام" }, { word: "برتقال", category: "طعام" },
  { word: "طماطم", category: "طعام" }, { word: "بطاطا", category: "طعام" },
  { word: "مكرونة", category: "طعام" }, { word: "بيتزا", category: "طعام" },
  { word: "برغر", category: "طعام" }, { word: "شاورما", category: "طعام" },
  { word: "كبسة", category: "طعام" }, { word: "مندي", category: "طعام" },
  { word: "مجبوس", category: "طعام" }, { word: "هريس", category: "طعام" },
  { word: "سمبوسة", category: "طعام" }, { word: "كنافة", category: "طعام" },
  { word: "بقلاوة", category: "طعام" }, { word: "لقيمات", category: "طعام" },
  { word: "مهلبية", category: "طعام" }, { word: "شوكولاته", category: "طعام" },
  { word: "بسكويت", category: "طعام" }, { word: "كيك", category: "طعام" },
  { word: "فطيرة", category: "طعام" }, { word: "سلطة", category: "طعام" },
  { word: "شوربة", category: "طعام" }, { word: "عدس", category: "طعام" },
  { word: "فول", category: "طعام" }, { word: "حمص", category: "طعام" },

  // ===================== مهنة =====================
  { word: "طبيب", category: "مهنة" }, { word: "معلم", category: "مهنة" },
  { word: "شرطي", category: "مهنة" }, { word: "طيار", category: "مهنة" },
  { word: "نجار", category: "مهنة" }, { word: "حداد", category: "مهنة" },
  { word: "خياط", category: "مهنة" }, { word: "طباخ", category: "مهنة" },
  { word: "صياد", category: "مهنة" }, { word: "ممرض", category: "مهنة" },
  { word: "صحفي", category: "مهنة" }, { word: "مصور", category: "مهنة" },
  { word: "نادل", category: "مهنة" }, { word: "بحار", category: "مهنة" },
  { word: "جندي", category: "مهنة" }, { word: "مهندس", category: "مهنة" },
  { word: "محامي", category: "مهنة" }, { word: "مزارع", category: "مهنة" },
  { word: "قاضي", category: "مهنة" }, { word: "محرر", category: "مهنة" },
  { word: "مترجم", category: "مهنة" }, { word: "مبرمج", category: "مهنة" },
  { word: "محاسب", category: "مهنة" }, { word: "مصمم", category: "مهنة" },
  { word: "مدرب", category: "مهنة" }, { word: "حلاق", category: "مهنة" },
  { word: "سباك", category: "مهنة" }, { word: "كهربائي", category: "مهنة" },
  { word: "دهان", category: "مهنة" }, { word: "خباز", category: "مهنة" },
  { word: "جزار", category: "مهنة" }, { word: "بائع", category: "مهنة" },
  { word: "سائق", category: "مهنة" }, { word: "مضيف", category: "مهنة" },
  { word: "ممثل", category: "مهنة" }, { word: "مخرج", category: "مهنة" },
  { word: "كاتب", category: "مهنة" }, { word: "شاعر", category: "مهنة" },

  // ===================== مكان =====================
  { word: "جبل", category: "مكان" }, { word: "نهر", category: "مكان" },
  { word: "بحر", category: "مكان" }, { word: "وادي", category: "مكان" },
  { word: "جسر", category: "مكان" }, { word: "نفق", category: "مكان" },
  { word: "سوق", category: "مكان" }, { word: "غابة", category: "مكان" },
  { word: "واحة", category: "مكان" }, { word: "شلال", category: "مكان" },
  { word: "قلعة", category: "مكان" }, { word: "مطار", category: "مكان" },
  { word: "محطة", category: "مكان" }, { word: "مسجد", category: "مكان" },
  { word: "صحراء", category: "مكان" }, { word: "جزيرة", category: "مكان" },
  { word: "بحيرة", category: "مكان" }, { word: "ميناء", category: "مكان" },
  { word: "كهف", category: "مكان" }, { word: "تلة", category: "مكان" },
  { word: "هضبة", category: "مكان" }, { word: "سهل", category: "مكان" },
  { word: "خليج", category: "مكان" }, { word: "مضيق", category: "مكان" },
  { word: "منتزه", category: "مكان" }, { word: "سد", category: "مكان" },
  { word: "بركان", category: "مكان" }, { word: "منارة", category: "مكان" },
  { word: "مرسى", category: "مكان" }, { word: "رصيف", category: "مكان" },
  { word: "استاد", category: "مكان" }, { word: "ملعب", category: "مكان" },
  { word: "فندق", category: "مكان" }, { word: "متجر", category: "مكان" },
  { word: "مصنع", category: "مكان" }, { word: "مزرعة", category: "مكان" },
  { word: "سفارة", category: "مكان" }, { word: "بلدية", category: "مكان" },

  // ===================== عام =====================
  { word: "قلم", category: "عام" }, { word: "باب", category: "عام" },
  { word: "كتاب", category: "عام" }, { word: "ساعة", category: "عام" },
  { word: "شباك", category: "عام" }, { word: "مكتب", category: "عام" },
  { word: "مطبخ", category: "عام" }, { word: "غرفة", category: "عام" },
  { word: "هاتف", category: "عام" }, { word: "سرير", category: "عام" },
  { word: "مراة", category: "عام" }, { word: "مصباح", category: "عام" },
  { word: "تلفاز", category: "عام" }, { word: "مدرسة", category: "عام" },
  { word: "مكتبة", category: "عام" }, { word: "حديقة", category: "عام" },
  { word: "سيارة", category: "عام" }, { word: "طائرة", category: "عام" },
  { word: "حاسوب", category: "عام" }, { word: "مفتاح", category: "عام" },
  { word: "سلطان", category: "عام" }, { word: "جميلة", category: "عام" },
  { word: "كبيرة", category: "عام" }, { word: "صغيرة", category: "عام" },
  { word: "جريدة", category: "عام" }, { word: "مدينة", category: "عام" },
  { word: "قصيدة", category: "عام" }, { word: "حقيبة", category: "عام" },
  { word: "عاصمة", category: "عام" }, { word: "جامعة", category: "عام" },
  { word: "سفينة", category: "عام" }, { word: "طويلة", category: "عام" },
  { word: "قصيرة", category: "عام" }, { word: "جديدة", category: "عام" },
  { word: "قديمة", category: "عام" }, { word: "رخيصة", category: "عام" },
  { word: "غالية", category: "عام" }, { word: "لذيذة", category: "عام" },
  { word: "باردة", category: "عام" }, { word: "سعيدة", category: "عام" },
  { word: "حزينة", category: "عام" }, { word: "نظيفة", category: "عام" },
  { word: "سريعة", category: "عام" }, { word: "بطيئة", category: "عام" },
  { word: "ثقيلة", category: "عام" }, { word: "خفيفة", category: "عام" },
  { word: "عريضة", category: "عام" }, { word: "مريضة", category: "عام" },
  { word: "جائعة", category: "عام" }, { word: "عطشان", category: "عام" },
  { word: "غضبان", category: "عام" }, { word: "فرحان", category: "عام" },
  { word: "تعبان", category: "عام" }, { word: "كسلان", category: "عام" },
  { word: "شجاعة", category: "عام" }, { word: "كريمة", category: "عام" },
  { word: "بخيلة", category: "عام" }, { word: "صادقة", category: "عام" },
  { word: "كاذبة", category: "عام" }, { word: "مجتهد", category: "عام" },
  { word: "طاولة", category: "عام" }, { word: "عمارة", category: "عام" },
  { word: "سحابة", category: "عام" }, { word: "بستان", category: "عام" },
  { word: "كنيسة", category: "عام" }, { word: "دراجة", category: "عام" },
  { word: "مروحة", category: "عام" }, { word: "غسالة", category: "عام" },
  { word: "ثلاجة", category: "عام" }, { word: "فرن", category: "عام" },
  { word: "صحن", category: "عام" }, { word: "ملعقة", category: "عام" },
  { word: "شوكة", category: "عام" }, { word: "سكين", category: "عام" },
  { word: "كوب", category: "عام" }, { word: "وسادة", category: "عام" },
  { word: "بطانية", category: "عام" }, { word: "ستارة", category: "عام" },
  { word: "سجادة", category: "عام" }, { word: "محفظة", category: "عام" },
  { word: "نظارة", category: "عام" }, { word: "قبعة", category: "عام" },
  { word: "حذاء", category: "عام" }, { word: "قميص", category: "عام" },
  { word: "بنطال", category: "عام" }, { word: "فستان", category: "عام" },
  { word: "معطف", category: "عام" }, { word: "جوارب", category: "عام" },

  // ===================== أنميات =====================
  { word: "ناروتو", category: "أنميات" }, { word: "بوكيمون", category: "أنميات" },
  { word: "كونان", category: "أنميات" }, { word: "بليتش", category: "أنميات" },
  { word: "دورايمون", category: "أنميات" }, { word: "غرندايزر", category: "أنميات" },
  { word: "ساسكي", category: "أنميات" }, { word: "لوفي", category: "أنميات" },
  { word: "غوكو", category: "أنميات" }, { word: "شينشان", category: "أنميات" },
  { word: "انوياشا", category: "أنميات" }, { word: "دراغون بول", category: "أنميات" },
  { word: "ون بيس", category: "أنميات" }, { word: "يوغي", category: "أنميات" },
  { word: "ديجيمون", category: "أنميات" }, { word: "سايلور مون", category: "أنميات" },
  { word: "غاندام", category: "أنميات" }, { word: "بلاك كلوفر", category: "أنميات" },
  { word: "توكيو غول", category: "أنميات" },

  // ===================== مسلسلات (مسلسلات كويتية) =====================
  { word: "الفريج", category: "مسلسلات" }, { word: "وحوش", category: "مسلسلات" },
  { word: "ساق البامبو", category: "مسلسلات" }, { word: "دفعة القاهرة", category: "مسلسلات" },
  { word: "امينة حاف", category: "مسلسلات" }, { word: "امر اخلاء", category: "مسلسلات" },
  { word: "درب الزلق", category: "مسلسلات" }, { word: "خالتي قماشة", category: "مسلسلات" },
  { word: "رقية وسبيكة", category: "مسلسلات" }, { word: "الغرباء", category: "مسلسلات" },
  { word: "بدر الزمان", category: "مسلسلات" }, { word: "الابريق المكسور", category: "مسلسلات" },
  { word: "علاء الدين", category: "مسلسلات" }, { word: "خرج ولم يعد", category: "مسلسلات" },
  { word: "الاسوار", category: "مسلسلات" }, { word: "حبابة", category: "مسلسلات" },
  { word: "سليمان الطيب", category: "مسلسلات" }, { word: "بوهباش", category: "مسلسلات" },
  { word: "يوميات متقاعد", category: "مسلسلات" }, { word: "الملقوفة", category: "مسلسلات" },
  { word: "على الدنيا السلام", category: "مسلسلات" },

  // ===================== كرتون قديم =====================
  { word: "عدنان", category: "كرتون قديم" }, { word: "كبامارو", category: "كرتون قديم" },
  { word: "ماروكو", category: "كرتون قديم" }, { word: "هايدي", category: "كرتون قديم" },
  { word: "سالي", category: "كرتون قديم" }, { word: "ماجد", category: "كرتون قديم" },
  { word: "غوليفر", category: "كرتون قديم" }, { word: "سندريلا", category: "كرتون قديم" },
  { word: "بامبي", category: "كرتون قديم" }, { word: "بينوكيو", category: "كرتون قديم" },
  { word: "بوباي", category: "كرتون قديم" }, { word: "بوجي", category: "كرتون قديم" },
  { word: "السنافر", category: "كرتون قديم" }, { word: "توم وجيري", category: "كرتون قديم" },
  { word: "ميكي ماوس", category: "كرتون قديم" }, { word: "ليدي اوسكار", category: "كرتون قديم" },
  { word: "الرحالة الصغير", category: "كرتون قديم" },

  // ===================== أسماء =====================
  { word: "محمد", category: "أسماء" }, { word: "احمد", category: "أسماء" },
  { word: "خالد", category: "أسماء" }, { word: "سالم", category: "أسماء" },
  { word: "فهد", category: "أسماء" }, { word: "ناصر", category: "أسماء" },
  { word: "يوسف", category: "أسماء" }, { word: "عبدالله", category: "أسماء" },
  { word: "جابر", category: "أسماء" }, { word: "ابراهيم", category: "أسماء" },
  { word: "مريم", category: "أسماء" }, { word: "نورة", category: "أسماء" },
  { word: "سارة", category: "أسماء" }, { word: "هند", category: "أسماء" },
  { word: "موزة", category: "أسماء" }, { word: "شيخة", category: "أسماء" },
  { word: "خديجة", category: "أسماء" }, { word: "عائشة", category: "أسماء" },
  { word: "امل", category: "أسماء" }, { word: "ريم", category: "أسماء" },
  { word: "عبدالعزيز", category: "أسماء" }, { word: "عبدالرحمن", category: "أسماء" },
  { word: "سعود", category: "أسماء" }, { word: "فيصل", category: "أسماء" },
  { word: "طلال", category: "أسماء" }, { word: "بدر", category: "أسماء" },
  { word: "راشد", category: "أسماء" }, { word: "وليد", category: "أسماء" },
  { word: "عمر", category: "أسماء" }, { word: "علي", category: "أسماء" },
  { word: "حسين", category: "أسماء" }, { word: "حسن", category: "أسماء" },
  { word: "تركي", category: "أسماء" }, { word: "جاسم", category: "أسماء" },
  { word: "فارس", category: "أسماء" }, { word: "لطيفة", category: "أسماء" },
  { word: "فاطمة", category: "أسماء" }, { word: "عزيزة", category: "أسماء" },
  { word: "بدرية", category: "أسماء" }, { word: "منيرة", category: "أسماء" },
  { word: "دلال", category: "أسماء" }, { word: "هيا", category: "أسماء" },
  { word: "رهف", category: "أسماء" }, { word: "لمى", category: "أسماء" },
  { word: "جود", category: "أسماء" }, { word: "نوف", category: "أسماء" },
  { word: "شهد", category: "أسماء" }, { word: "جنى", category: "أسماء" },
  { word: "لولوة", category: "أسماء" }, { word: "مها", category: "أسماء" },

  // ===================== مسرحيات (مسرحيات كويتية قديمة) =====================
  { word: "عزوبي السالمية", category: "مسرحيات" }, { word: "باي باي لندن", category: "مسرحيات" },
  { word: "استارثوني وانا حي", category: "مسرحيات" }, { word: "على هامان يا فرعون", category: "مسرحيات" },
  { word: "بني صامت", category: "مسرحيات" }, { word: "سيف العرب", category: "مسرحيات" },
  { word: "باي باي عرب", category: "مسرحيات" }, { word: "حط الطير طار الطير", category: "مسرحيات" },
  { word: "فرحة امة", category: "مسرحيات" }, { word: "اسلام عمر", category: "مسرحيات" },
  { word: "حرب البسوس", category: "مسرحيات" }, { word: "فتح الاندلس", category: "مسرحيات" },
  { word: "صقر قريش", category: "مسرحيات" },

  // ===================== روايات (من سلسلة روائع الأدب العالمي) =====================
  { word: "مغامرات السندباد البحري", category: "روايات" }, { word: "رحلات جوليفر", category: "روايات" },
  { word: "مزرعة الحيوان", category: "روايات" }, { word: "جزيرة الكنز", category: "روايات" },
  { word: "روبنسون كروزو", category: "روايات" }, { word: "روبن هود", category: "روايات" },
  { word: "دراكولا", category: "روايات" }, { word: "فرانكنشتاين", category: "روايات" },
  { word: "موبي ديك", category: "روايات" }, { word: "الامير الصغير", category: "روايات" },
  { word: "كوخ العم توم", category: "روايات" }, { word: "ثلاثة رجال في قارب", category: "روايات" },
  { word: "اللؤلؤة", category: "روايات" }, { word: "عناقيد الغضب", category: "روايات" },
  { word: "روميو وجولييت", category: "روايات" }, { word: "مكبث", category: "روايات" },
  { word: "عطيل", category: "روايات" }, { word: "الملك لير", category: "روايات" },
  { word: "هملت", category: "روايات" }, { word: "الشيخ والبحر", category: "روايات" },
  { word: "وداعا للسلاح", category: "روايات" }, { word: "اليس في بلاد العجائب", category: "روايات" },
  { word: "مونتي كريستو", category: "روايات" }, { word: "الفرسان الثلاثة", category: "روايات" },
  { word: "اوليفر تويست", category: "روايات" }, { word: "توم سوير", category: "روايات" },
  { word: "مغامرات هاكلبري فين", category: "روايات" }, { word: "جين اير", category: "روايات" },
  { word: "كبرياء وهوى", category: "روايات" }, { word: "ذهب مع الريح", category: "روايات" },
  { word: "الاخوة كارامازوف", category: "روايات" }, { word: "انا كارنينا", category: "روايات" },
  { word: "مغامرات شيرلوك هولمز", category: "روايات" }, { word: "دموع التماسيح", category: "روايات" },
  { word: "قصة مدينتين", category: "روايات" }, { word: "مرتفعات وذرينغ", category: "روايات" },
  { word: "الامير والفقير", category: "روايات" }, { word: "اوقات صعبة", category: "روايات" },
  { word: "السهم الاسود", category: "روايات" }, { word: "كنوز الملك سليمان", category: "روايات" },
  { word: "نداء البراري", category: "روايات" }, { word: "نزل جامايكا", category: "روايات" },
  { word: "الحديقة السرية", category: "روايات" }, { word: "رجل من غلاسكو", category: "روايات" },

  // ===================== رياضة =====================
  { word: "كرة قدم", category: "رياضة" }, { word: "سباحة", category: "رياضة" },
  { word: "كرة سلة", category: "رياضة" }, { word: "تنس", category: "رياضة" },
  { word: "جري", category: "رياضة" }, { word: "ملاكمة", category: "رياضة" },
  { word: "جمباز", category: "رياضة" }, { word: "كرة طائرة", category: "رياضة" },
  { word: "جودو", category: "رياضة" }, { word: "كاراتيه", category: "رياضة" },
  { word: "هوكي", category: "رياضة" }, { word: "اسكواش", category: "رياضة" },
  { word: "مصارعة", category: "رياضة" }, { word: "دراجات", category: "رياضة" },
  { word: "غطس", category: "رياضة" }, { word: "جولف", category: "رياضة" },
  { word: "كرة يد", category: "رياضة" }, { word: "تايكوندو", category: "رياضة" },
  { word: "رفع اثقال", category: "رياضة" }, { word: "مبارزة", category: "رياضة" },
  { word: "رماية", category: "رياضة" }, { word: "تجديف", category: "رياضة" },
  { word: "ركوب خيل", category: "رياضة" }, { word: "بولينج", category: "رياضة" },
  { word: "بلياردو", category: "رياضة" }, { word: "كرلنغ", category: "رياضة" },
  { word: "تزلج", category: "رياضة" }, { word: "قفز", category: "رياضة" },
  { word: "وثب طويل", category: "رياضة" }, { word: "رمي جلة", category: "رياضة" },
  { word: "رمي رمح", category: "رياضة" }, { word: "شطرنج", category: "رياضة" },
  { word: "سباق", category: "رياضة" },

  // ===================== ألوان =====================
  { word: "ازرق", category: "ألوان" }, { word: "احمر", category: "ألوان" },
  { word: "اخضر", category: "ألوان" }, { word: "اصفر", category: "ألوان" },
  { word: "اسود", category: "ألوان" }, { word: "ابيض", category: "ألوان" },
  { word: "بنفسجي", category: "ألوان" }, { word: "وردي", category: "ألوان" },
  { word: "برتقالي", category: "ألوان" }, { word: "بني", category: "ألوان" },
  { word: "رمادي", category: "ألوان" }, { word: "ذهبي", category: "ألوان" },
  { word: "فضي", category: "ألوان" }, { word: "فيروزي", category: "ألوان" },
  { word: "تركواز", category: "ألوان" }, { word: "كحلي", category: "ألوان" },
  { word: "بيج", category: "ألوان" }, { word: "عنابي", category: "ألوان" },
  { word: "سماوي", category: "ألوان" }, { word: "نيلي", category: "ألوان" },
  { word: "زهري", category: "ألوان" }, { word: "خمري", category: "ألوان" },
  { word: "زيتي", category: "ألوان" }, { word: "ياقوتي", category: "ألوان" },
  { word: "قرمزي", category: "ألوان" }, { word: "ارجواني", category: "ألوان" },
  { word: "كريمي", category: "ألوان" }, { word: "رصاصي", category: "ألوان" },
  { word: "لؤلؤي", category: "ألوان" }, { word: "مرجاني", category: "ألوان" },
  { word: "ليموني", category: "ألوان" }, { word: "برونزي", category: "ألوان" },
  { word: "نحاسي", category: "ألوان" }, { word: "موف", category: "ألوان" },
  { word: "عاجي", category: "ألوان" },

  // ===================== مناطق الكويت =====================
  { word: "السرة", category: "مناطق الكويت" }, { word: "الجابرية", category: "مناطق الكويت" },
  { word: "فنيطيس", category: "مناطق الكويت" }, { word: "سلوى", category: "مناطق الكويت" },
  { word: "السالمية", category: "مناطق الكويت" }, { word: "حولي", category: "مناطق الكويت" },
  { word: "الفروانية", category: "مناطق الكويت" }, { word: "الجهراء", category: "مناطق الكويت" },
  { word: "بيان", category: "مناطق الكويت" }, { word: "الرميثية", category: "مناطق الكويت" },
  { word: "اليرموك", category: "مناطق الكويت" }, { word: "قرطبة", category: "مناطق الكويت" },
  { word: "الشامية", category: "مناطق الكويت" }, { word: "كيفان", category: "مناطق الكويت" },
  { word: "الدسمة", category: "مناطق الكويت" }, { word: "الروضة", category: "مناطق الكويت" },
  { word: "القادسية", category: "مناطق الكويت" }, { word: "خيطان", category: "مناطق الكويت" },
  { word: "دسمان", category: "مناطق الكويت" }, { word: "الشرق", category: "مناطق الكويت" },
  { word: "الصوابر", category: "مناطق الكويت" }, { word: "المرقاب", category: "مناطق الكويت" },
  { word: "القبلة", category: "مناطق الكويت" }, { word: "الصالحية", category: "مناطق الكويت" },
  { word: "الوطية", category: "مناطق الكويت" }, { word: "المنصورية", category: "مناطق الكويت" },
  { word: "العديلية", category: "مناطق الكويت" }, { word: "النزهة", category: "مناطق الكويت" },
  { word: "الدوحة", category: "مناطق الكويت" }, { word: "الخالدية", category: "مناطق الكويت" },
  { word: "الفيحاء", category: "مناطق الكويت" }, { word: "الدعية", category: "مناطق الكويت" },
  { word: "الصليبيخات", category: "مناطق الكويت" }, { word: "غرناطة", category: "مناطق الكويت" },
  { word: "جابر الاحمد", category: "مناطق الكويت" }, { word: "عبدالله السالم", category: "مناطق الكويت" },
  { word: "القيروان", category: "مناطق الكويت" }, { word: "النهضة", category: "مناطق الكويت" },
  { word: "بنيد القار", category: "مناطق الكويت" }, { word: "الشويخ", category: "مناطق الكويت" },
  { word: "مشرف", category: "مناطق الكويت" }, { word: "الشعب", category: "مناطق الكويت" },
  { word: "السلام", category: "مناطق الكويت" }, { word: "حطين", category: "مناطق الكويت" },
  { word: "الزهراء", category: "مناطق الكويت" }, { word: "مبارك العبدالله", category: "مناطق الكويت" },
  { word: "الشهداء", category: "مناطق الكويت" }, { word: "البدع", category: "مناطق الكويت" },
  { word: "الصديق", category: "مناطق الكويت" }, { word: "النقرة", category: "مناطق الكويت" },
  { word: "الاندلس", category: "مناطق الكويت" }, { word: "اشبيلية", category: "مناطق الكويت" },
  { word: "ابرق خيطان", category: "مناطق الكويت" }, { word: "العارضية", category: "مناطق الكويت" },
  { word: "الفردوس", category: "مناطق الكويت" }, { word: "صباح الناصر", category: "مناطق الكويت" },
  { word: "عبدالله المبارك", category: "مناطق الكويت" }, { word: "الضجيج", category: "مناطق الكويت" },
  { word: "الشدادية", category: "مناطق الكويت" }, { word: "العمرية", category: "مناطق الكويت" },
  { word: "الرابية", category: "مناطق الكويت" }, { word: "الرحاب", category: "مناطق الكويت" },
  { word: "الرقعي", category: "مناطق الكويت" }, { word: "جليب الشيوخ", category: "مناطق الكويت" },
  { word: "الواحة", category: "مناطق الكويت" }, { word: "العيون", category: "مناطق الكويت" },
  { word: "القصر", category: "مناطق الكويت" }, { word: "النسيم", category: "مناطق الكويت" },
  { word: "تيماء", category: "مناطق الكويت" }, { word: "النعيم", category: "مناطق الكويت" },
  { word: "سعد العبدالله", category: "مناطق الكويت" }, { word: "كاظمة", category: "مناطق الكويت" },
  { word: "الروضتين", category: "مناطق الكويت" }, { word: "ام العيش", category: "مناطق الكويت" },
  { word: "السالمي", category: "مناطق الكويت" }, { word: "كبد", category: "مناطق الكويت" },
  { word: "الصليبية", category: "مناطق الكويت" }, { word: "امغرة", category: "مناطق الكويت" },
  { word: "خباري العوازم", category: "مناطق الكويت" }, { word: "الصبية", category: "مناطق الكويت" },
  { word: "المطلاع", category: "مناطق الكويت" }, { word: "العبدلي", category: "مناطق الكويت" },
  { word: "بوبيان", category: "مناطق الكويت" }, { word: "وربة", category: "مناطق الكويت" },
  { word: "صباح السالم", category: "مناطق الكويت" }, { word: "المسيلة", category: "مناطق الكويت" },
  { word: "العدان", category: "مناطق الكويت" }, { word: "القصور", category: "مناطق الكويت" },
  { word: "القرين", category: "مناطق الكويت" }, { word: "الوسطى", category: "مناطق الكويت" },
  { word: "صبحان", category: "مناطق الكويت" },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { WORDS };
}
