// بنك الكلمات للعبة "احزر الكلمة" - كل كلمة عربية فصحى بدون تشكيل، مع فئة تستخدم في زر التلميح
// طول الكلمات يتراوح بين 3 و8 أحرف ويُختار عشوائياً عند بدء كل جولة

const WORDS = [
  // ===================== دولة =====================
  { word: "مصر", category: "دولة" },
  { word: "قطر", category: "دولة" },
  { word: "عمان", category: "دولة" },
  { word: "تونس", category: "دولة" },
  { word: "ليبيا", category: "دولة" },
  { word: "سوريا", category: "دولة" },
  { word: "اليمن", category: "دولة" },
  { word: "لبنان", category: "دولة" },
  { word: "الهند", category: "دولة" },
  { word: "الصين", category: "دولة" },
  { word: "العراق", category: "دولة" },
  { word: "المغرب", category: "دولة" },
  { word: "الاردن", category: "دولة" },
  { word: "السودان", category: "دولة" },
  { word: "الجزائر", category: "دولة" },
  { word: "البحرين", category: "دولة" },
  { word: "الصومال", category: "دولة" },
  { word: "السعودية", category: "دولة" },

  // ===================== تاريخ =====================
  { word: "حرب", category: "تاريخ" },
  { word: "فتح", category: "تاريخ" },
  { word: "غزو", category: "تاريخ" },
  { word: "عصر", category: "تاريخ" },
  { word: "قرن", category: "تاريخ" },
  { word: "زمن", category: "تاريخ" },
  { word: "ثورة", category: "تاريخ" },
  { word: "معركة", category: "تاريخ" },
  { word: "حضارة", category: "تاريخ" },
  { word: "وثيقة", category: "تاريخ" },
  { word: "تحرير", category: "تاريخ" },
  { word: "مملكة", category: "تاريخ" },
  { word: "خلافة", category: "تاريخ" },
  { word: "معاهدة", category: "تاريخ" },
  { word: "احتلال", category: "تاريخ" },
  { word: "استقلال", category: "تاريخ" },
  { word: "استعمار", category: "تاريخ" },

  // ===================== حيوان =====================
  { word: "اسد", category: "حيوان" },
  { word: "نمر", category: "حيوان" },
  { word: "ذئب", category: "حيوان" },
  { word: "فيل", category: "حيوان" },
  { word: "جمل", category: "حيوان" },
  { word: "قرد", category: "حيوان" },
  { word: "نسر", category: "حيوان" },
  { word: "صقر", category: "حيوان" },
  { word: "حوت", category: "حيوان" },
  { word: "قطة", category: "حيوان" },
  { word: "كلب", category: "حيوان" },
  { word: "حصان", category: "حيوان" },
  { word: "ارنب", category: "حيوان" },
  { word: "ثعلب", category: "حيوان" },
  { word: "خروف", category: "حيوان" },
  { word: "غزال", category: "حيوان" },
  { word: "بومة", category: "حيوان" },
  { word: "زرافة", category: "حيوان" },
  { word: "تمساح", category: "حيوان" },
  { word: "فراشة", category: "حيوان" },
  { word: "عصفور", category: "حيوان" },
  { word: "حمامة", category: "حيوان" },
  { word: "دجاجة", category: "حيوان" },
  { word: "عنكبوت", category: "حيوان" },

  // ===================== طعام =====================
  { word: "خبز", category: "طعام" },
  { word: "تمر", category: "طعام" },
  { word: "ارز", category: "طعام" },
  { word: "لحم", category: "طعام" },
  { word: "سمك", category: "طعام" },
  { word: "عسل", category: "طعام" },
  { word: "موز", category: "طعام" },
  { word: "شاي", category: "طعام" },
  { word: "جبن", category: "طعام" },
  { word: "سكر", category: "طعام" },
  { word: "ملح", category: "طعام" },
  { word: "زيت", category: "طعام" },
  { word: "خيار", category: "طعام" },
  { word: "زبدة", category: "طعام" },
  { word: "حليب", category: "طعام" },
  { word: "قهوة", category: "طعام" },
  { word: "عصير", category: "طعام" },
  { word: "تفاح", category: "طعام" },
  { word: "فطور", category: "طعام" },
  { word: "خيارة", category: "طعام" },
  { word: "فاكهة", category: "طعام" },
  { word: "برتقال", category: "طعام" },
  { word: "طماطم", category: "طعام" },
  { word: "بطاطا", category: "طعام" },

  // ===================== مهنة =====================
  { word: "طبيب", category: "مهنة" },
  { word: "معلم", category: "مهنة" },
  { word: "شرطي", category: "مهنة" },
  { word: "طيار", category: "مهنة" },
  { word: "نجار", category: "مهنة" },
  { word: "حداد", category: "مهنة" },
  { word: "خياط", category: "مهنة" },
  { word: "طباخ", category: "مهنة" },
  { word: "صياد", category: "مهنة" },
  { word: "ممرض", category: "مهنة" },
  { word: "صحفي", category: "مهنة" },
  { word: "مصور", category: "مهنة" },
  { word: "نادل", category: "مهنة" },
  { word: "بحار", category: "مهنة" },
  { word: "جندي", category: "مهنة" },
  { word: "مهندس", category: "مهنة" },
  { word: "محامي", category: "مهنة" },
  { word: "مزارع", category: "مهنة" },

  // ===================== مكان =====================
  { word: "جبل", category: "مكان" },
  { word: "نهر", category: "مكان" },
  { word: "بحر", category: "مكان" },
  { word: "وادي", category: "مكان" },
  { word: "جسر", category: "مكان" },
  { word: "نفق", category: "مكان" },
  { word: "سوق", category: "مكان" },
  { word: "غابة", category: "مكان" },
  { word: "واحة", category: "مكان" },
  { word: "شلال", category: "مكان" },
  { word: "قلعة", category: "مكان" },
  { word: "مطار", category: "مكان" },
  { word: "محطة", category: "مكان" },
  { word: "مسجد", category: "مكان" },
  { word: "صحراء", category: "مكان" },
  { word: "جزيرة", category: "مكان" },
  { word: "بحيرة", category: "مكان" },
  { word: "ميناء", category: "مكان" },

  // ===================== عام =====================
  { word: "قلم", category: "عام" },
  { word: "باب", category: "عام" },
  { word: "كتاب", category: "عام" },
  { word: "ساعة", category: "عام" },
  { word: "شباك", category: "عام" },
  { word: "مكتب", category: "عام" },
  { word: "مطبخ", category: "عام" },
  { word: "غرفة", category: "عام" },
  { word: "هاتف", category: "عام" },
  { word: "سرير", category: "عام" },
  { word: "مراة", category: "عام" },
  { word: "مصباح", category: "عام" },
  { word: "تلفاز", category: "عام" },
  { word: "مدرسة", category: "عام" },
  { word: "مكتبة", category: "عام" },
  { word: "حديقة", category: "عام" },
  { word: "سيارة", category: "عام" },
  { word: "طائرة", category: "عام" },
  { word: "حاسوب", category: "عام" },
  { word: "مفتاح", category: "عام" },
  { word: "سلطان", category: "عام" },
  { word: "جميلة", category: "عام" },
  { word: "كبيرة", category: "عام" },
  { word: "صغيرة", category: "عام" },
  { word: "جريدة", category: "عام" },
  { word: "مدينة", category: "عام" },
  { word: "قصيدة", category: "عام" },
  { word: "حقيبة", category: "عام" },
  { word: "عاصمة", category: "عام" },
  { word: "جامعة", category: "عام" },
  { word: "سفينة", category: "عام" },
  { word: "طويلة", category: "عام" },
  { word: "قصيرة", category: "عام" },
  { word: "جديدة", category: "عام" },
  { word: "قديمة", category: "عام" },
  { word: "رخيصة", category: "عام" },
  { word: "غالية", category: "عام" },
  { word: "لذيذة", category: "عام" },
  { word: "باردة", category: "عام" },
  { word: "سعيدة", category: "عام" },
  { word: "حزينة", category: "عام" },
  { word: "نظيفة", category: "عام" },
  { word: "سريعة", category: "عام" },
  { word: "بطيئة", category: "عام" },
  { word: "ثقيلة", category: "عام" },
  { word: "خفيفة", category: "عام" },
  { word: "عريضة", category: "عام" },
  { word: "مريضة", category: "عام" },
  { word: "جائعة", category: "عام" },
  { word: "عطشان", category: "عام" },
  { word: "غضبان", category: "عام" },
  { word: "فرحان", category: "عام" },
  { word: "تعبان", category: "عام" },
  { word: "كسلان", category: "عام" },
  { word: "شجاعة", category: "عام" },
  { word: "كريمة", category: "عام" },
  { word: "بخيلة", category: "عام" },
  { word: "صادقة", category: "عام" },
  { word: "كاذبة", category: "عام" },
  { word: "مجتهد", category: "عام" },
  { word: "طاولة", category: "عام" },
  { word: "عمارة", category: "عام" },
  { word: "سحابة", category: "عام" },
  { word: "بستان", category: "عام" },
  { word: "كنيسة", category: "عام" },
  { word: "دراجة", category: "عام" },

  // ===================== أنميات =====================
  { word: "ناروتو", category: "أنميات" },
  { word: "بوكيمون", category: "أنميات" },
  { word: "كونان", category: "أنميات" },
  { word: "بليتش", category: "أنميات" },
  { word: "دورايمون", category: "أنميات" },
  { word: "غرندايزر", category: "أنميات" },
  { word: "ساسكي", category: "أنميات" },
  { word: "لوفي", category: "أنميات" },
  { word: "غوكو", category: "أنميات" },
  { word: "شينشان", category: "أنميات" },
  { word: "انوياشا", category: "أنميات" },

  // ===================== مسلسلات (مسلسلات كويتية) =====================
  { word: "الفريج", category: "مسلسلات" },
  { word: "وحوش", category: "مسلسلات" },
  { word: "ساق البامبو", category: "مسلسلات" },
  { word: "دفعة القاهرة", category: "مسلسلات" },
  { word: "امينة حاف", category: "مسلسلات" },
  { word: "امر اخلاء", category: "مسلسلات" },
  { word: "درب الزلق", category: "مسلسلات" },
  { word: "خالتي قماشة", category: "مسلسلات" },
  { word: "رقية وسبيكة", category: "مسلسلات" },
  { word: "الغرباء", category: "مسلسلات" },
  { word: "بدر الزمان", category: "مسلسلات" },
  { word: "الابريق المكسور", category: "مسلسلات" },
  { word: "علاء الدين", category: "مسلسلات" },
  { word: "خرج ولم يعد", category: "مسلسلات" },

  // ===================== كرتون قديم =====================
  { word: "عدنان", category: "كرتون قديم" },
  { word: "كبامارو", category: "كرتون قديم" },
  { word: "ماروكو", category: "كرتون قديم" },
  { word: "هايدي", category: "كرتون قديم" },
  { word: "سالي", category: "كرتون قديم" },
  { word: "ماجد", category: "كرتون قديم" },
  { word: "غوليفر", category: "كرتون قديم" },
  { word: "سندريلا", category: "كرتون قديم" },
  { word: "بامبي", category: "كرتون قديم" },
  { word: "بينوكيو", category: "كرتون قديم" },
  { word: "بوباي", category: "كرتون قديم" },
  { word: "بوجي", category: "كرتون قديم" },

  // ===================== أسماء =====================
  { word: "محمد", category: "أسماء" },
  { word: "احمد", category: "أسماء" },
  { word: "خالد", category: "أسماء" },
  { word: "سالم", category: "أسماء" },
  { word: "فهد", category: "أسماء" },
  { word: "ناصر", category: "أسماء" },
  { word: "يوسف", category: "أسماء" },
  { word: "عبدالله", category: "أسماء" },
  { word: "جابر", category: "أسماء" },
  { word: "ابراهيم", category: "أسماء" },
  { word: "مريم", category: "أسماء" },
  { word: "نورة", category: "أسماء" },
  { word: "سارة", category: "أسماء" },
  { word: "هند", category: "أسماء" },
  { word: "موزة", category: "أسماء" },
  { word: "شيخة", category: "أسماء" },
  { word: "خديجة", category: "أسماء" },
  { word: "عائشة", category: "أسماء" },
  { word: "امل", category: "أسماء" },
  { word: "ريم", category: "أسماء" },
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { WORDS };
}
